"""
User facing strings should be defined here and referenced by variable as needed
"""

VERSION_LABEL = "Version"
LANGUAGE_LABEL = "Language:"
OPTIONS_PANEL = "Options"
DARK_OPTION = "Dark Mode"
GAME_TITLE = "Frog Game"
PLAY_BUTTON = "Play Game"
HIGHSCORES_BUTTON = "High Scores"
GAME_COPYRIGHT = "© 2022 Pythonic Four"
THEME_COPYRIGHT = "© 2021 rdbende"
THEME_NAME = "Sun-Valley-ttk-theme"
LEADERBOARD_TITLE = "High Scores"
MAIN_MENU_BUTTON = "Return to Main Menu"
BACK_BUTTON = "Go Back"
PAUSE_BUTTON = "Pause Game"
UNPAUSE_BUTTON = "Unpause Game"
TIMER_LABEL = "Timer: "
PAUSED_TEXT = "PAUSED"
START_BUTTON = "Start Game"
QUIT_MESSAGE = "Are you sure you want to quit?\nCurrent progess will be lost!"
NUM_FROGS_LABEL = "Number of Frogs:"
HOWTO_SHORT_LABEL = "To win, get all frogs on the same lilypad! Watch out though, frogs on the same space jump together. Each frog on the lilypad adds one jump to the total number of jumps they ALL will make. You can only jump frogs to a lilypad that already has frogs."
HINT_LABEL = "HINT: The more frogs, the higher your score, but the harder the game!"
RELOAD_APP = "Reloading Application"
RELOAD_APP_MSG = (
    "This change requires an application reload. Do you wish to reload now?"
)

ARROW_LEFT = "<< "
ARROW_RIGHT = " >>"

WELCOME_SCREEN = "Main Menu"
GAMEBOARD_SCREEN = "Game"
LEADERBOARD_SCREEN = "High Scores"
HELP_SCREEN = "Help"
