"""
User facing strings should be defined here and referenced by variable as needed
"""

OPTIONS_PANEL = "Options"
DARK_OPTION = "Dark Mode"
GAME_TITLE = "Frog Game"
PLAY_BUTTON = "Play Game"
HIGHSCORES_BUTTON = "High Scores"
GAME_COPYRIGHT = "© 2022 Pythonic Four"
THEME_COPYRIGHT = "© 2021 rdbende"
THEME_NAME = "Sun-Valley-ttk-theme"
LEADERBOARD_TITLE = "High Scores"
MAIN_MENU_BUTTON = "Return to Main Menu"
BACK_BUTTON = "Go Back"
PAUSE_BUTTON = "Pause Game"
UNPAUSE_BUTTON = "Unpause Game"
TIMER_LABEL = "Timer: "

ARROW_LEFT = "<< "
ARROW_RIGHT = " >>"

WELCOME_SCREEN = "Main Menu"
GAMEBOARD_SCREEN = "Game"
LEADERBOARD_SCREEN = "High Scores"
HELP_SCREEN = "Help"
